<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class GothraSeeder extends Seeder
{
    public function run(): void
    {
        $gothras = [
            "Aatharvas",
            "Agasthi",
            "Ahabhunasa",
            "Airan",
            "Alampayana",
            "Angiras",
            "Arrishinimi",
            "Athreyasya / Athreyasa",
            "Atri",
            "Attarishi",
            "Aukshanas",
            "Aushanas",
            "Babrahvya",
            "Badarayana",
            "Baijvayas",
            "Bansal",
            "Bashan",
            "Bhandal",
            "Bharadwaj",
            "Bhargava/Bhargav",
            "Bhasyan",
            "Bhrigu",
            "Bindal",
            "Birthare",
            "Bodhaaynas",
            "Chandratri",
            "Chikithasa",
            "Chyavanasa",
            "Daksa",
            "Dalabhya",
            "Darbhas",
            "Devrata",
            "Dhananjaya",
            "Dhanvantri",
            "Dhara Gautam",
            "Dharan",
            "Dharanas",
            "Dixit",
            "Duttatreyas",
            "Galiva",
            "Ganganas",
            "Gangyanas",
            "Gardhmukh Sandilya",
            "Garg",
            "Garga / Gargya",
            "Gargya Sainasa",
            "Gautam / Gouthama",
            "Ghrit Kaushika",
            "Gowri Veetham",
            "Goyal",
            "Goyan",
            "Haritasya / Harithasa / Haritha",
            "Jaiminiyas",
            "Jamadagni",
            "Jatukarna",
            "Jindal",
            "Kaakavas",
            "Kabi",
            "Kalabouddasa",
            "Kalpangeerasa",
            "Kamakayana Vishwamitra",
            "Kamsa",
            "Kanav",
            "Kansal",
            "Kanva",
            "Kapi",
            "Kapila Baradwaj",
            "Kapinjal",
            "Kapishthalas",
            "Kaplish",
            "Kashish",
            "Kashyapa / Kaashyapa",
            "Katyayan / Katyan",
            "Kaundinya / Koundanya / Kaundilya",
            "Kaunsa",
            "Kaushal",
            "Kaushika / Kaushik / Kausikasa",
            "Keshoryas",
            "Koushika Visvamitrasa",
            "Krishnatrey",
            "Kucchal",
            "Kusa",
            "Kutsa / Kutsas / Kutsasa",
            "Laakshmanas",
            "Laugakshi",
            "Lavania",
            "Lodwan",
            "Lohit",
            "Lokaakhyas",
            "Lomasha",
            "Madelia",
            "Madhukul",
            "Maitraya",
            "Manava",
            "Mandavya",
            "Mangal",
            "Marica",
            "Markendeya",
            "Maudlas",
            "Maunas",
            "Mihir",
            "Mittal",
            "Moudgalya",
            "Mouna Bhargava",
            "Munish",
            "Mythravaruna",
            "Naagal",
            "Nagasya",
            "Naidrupa Kashyapa",
            "Narayanas",
            "Nithyandala",
            "Paaniyas",
            "Pachori",
            "Paing",
            "Parashar / Parashara",
            "Parthivasa",
            "Paulastya",
            "Poothamanasa",
            "Pourugutsa",
            "Prachinas",
            "Raghuvanshi",
            "Rajoria",
            "Rathitar",
            "Rohinya",
            "Rohita",
            "Sakalya",
            "Sakhyanasa",
            "Salankayanasa",
            "Sankash",
            "Sankha-Pingala-Kausta",
            "Sankrut",
            "Sankyanasa",
            "Savanaka",
            "Savarana / Sabarna / Savarna / Sraborno",
            "Shaalaksha",
            "Shadamarshana / Shatamarshanam",
            "Shakhanas",
            "Shalavatsa",
            "Shandilya / Sandilyasa",
            "Sharkaras",
            "Sharkvas",
            "Shaunak",
            "Shravanesya",
            "Shrimukh Shandilya",
            "Shukla Atreyas",
            "Sigidha",
            "Singhal",
            "Sri Vatsa / Vatsa / Vats / Vacchas",
            "Srungi Bharadwajasa",
            "Suparnasa",
            "Swathantra Kapisa",
            "Tayal",
            "Tharakayanam",
            "Thingal",
            "Titwal",
            "Tushar",
            "Udbahu",
            "Udhalaka",
            "Uditha Gautham",
            "Udithya",
            "Upamanyu Vasishtasa",
            "Upamanyu",
            "Upathya",
            "Vadoola / Vadulasa",
            "Vainya",
            "Vardheyasa",
            "Vashishtha",
            "Veethahavya",
            "Vishnordhageerasa",
            "Vishnu Vridhha",
            "Vishwamitra",
            "Yaska",
            "Others",
            "Don't know"
        ];

        foreach ($gothras as $name) {
            DB::table('gothras')->insert([
                'name' => $name,
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        }
    }
}
